export const SCREEN_NAMES = {
  home: 'home',
  login: 'login',
  firstLogin: 'firstLogin',
  listen: 'listen',
  record: 'record',
  settings: 'settings',
  game: 'game',
  settingsNavigator: 'settings-navigator',
  settingsProfile: 'settings-profile',
  recordNavigator: 'record-navigator',
  wordsRecord: 'words-record',
  myRecordListen: 'my-record-listen',
  listeningsNavigator: 'listeningsNavigator',
  searchListen: 'searchListen',
  individual: 'individual',
  listenDetailScreen: 'individualDetail',
  listAudioListenScreen: 'listAudioListenScreen',
  mainGroup: 'mainGroup',
  createGroup: 'createGroup',
};
