
// Login
POST  http://localhost:5000/api/auth/login
Content-Type:  application/json

{
    "username":"test1",
    "password":"111111"
}


###
POST  http://localhost:5000/api/auth/register
Content-Type:  application/json

{
    "username":"test6",
    "password":"111111",
    "confirmPassword":"111111"
}