
// Login
POST  http://10.0.100.81:5000/api/auth/login
Content-Type:  application/json

{
    "email":"user@example.com",
    "userId":"123"
}


###
POST  http://10.0.100.81:5000/api/auth/register
Content-Type:  application/json

{
  "userId": "123",
  "avatar": "avatar.jpg",
  "email": "user@example.com",
  "department": "HR",
  "displayName": "John",
  "fullName": "John Doe",
  "nativeLanguage": "English",
  "role": "Employee"
}